steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/livecamera', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/livecamera']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - run
      - deploy
      - livecamera
      - --image=gcr.io/$PROJECT_ID/livecamera
      - --region=us-central1
      - --platform=managed
      - --timeout=3600
      - --session-affinity

options:
  logging: CLOUD_LOGGING_ONLY
